export { default as Forgery } from './Forgery.svelte'
export { default as Teachers } from './Teachers.svelte'
export { default as Upload } from './Upload.svelte'
export { default as Login } from './Login.svelte'
export { default as Logo } from './Logo.svelte'
export { default as Search } from './Search.svelte'
export { default as NavButton } from './internal/NavButton.svelte'
export { default as Link } from './internal/Link.svelte'
// @ts-expect-error
export { go } from './internal/Link.svelte'
