[build]
publish = "web/dist"
functions = ".netlify/functions"
command = "make -j2 build"

[build.environment]
FUNCTIONS_URL = "/.netlify/functions/index"
NODE_VERSION = "15"
GO_IMPORT_PATH = "github.com/FiveIT/template"
CYPRESS_CACHE_FOLDER = "node_modules/CypressBinary"
TERM = "xterm"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = ["web/node_modules", "web/.routify", ".pnpm-store"]

[[plugins]]
package = "netlify-plugin-cypress"
  [plugins.inputs]
  record = true
  group = "deployed"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
