version: 3
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
# TODO: Create function for retrieving randomly ordered list of works from the database
